FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/

COPY processed_data/movie_id_map.parquet processed_data/
COPY processed_data/genome_embeddings.npy processed_data/
COPY processed_data/links.csv processed_data/

EXPOSE 8501
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0


CMD ["streamlit", "run", "src/frontend.py"]
